name: firebase_crud
description: A firebase project with Rx Dart.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.4.2
  rxdart: ^0.28.0
  image_picker: ^1.1.2
  flutter_hooks: ^0.20.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.27.1
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  awesome_notifications: ^0.9.3+1
  awesome_notifications_fcm: ^0.9.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^2.1.7

icons_launcher:
  image_path: "assets/icons/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
